### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by LizIsTired** [LizIsTired/cave_dust#12]

**Comment by LizIsTired** [comment]
Have to wait for [Kirin ](https://github.com/MineLittlePony/Kirin) to update to 1.20 before porting myself.

**Comment by Ultimushadow** [comment]
Hey, not sure if you're aware but it looks like Kirin had a 1.20 release 3 weeks ago, I hope it's good to use for an update!

**Comment by LizIsTired** [comment]
Thank you! I had found the release a little bit ago but have been busy, 1.20.1 version will be releasing soon!

**Comment by LizIsTired** [comment]
Updated and uploaded, awaiting approval :)

**Comment by Ultimushadow** [comment]
Thanks for the update! Glad to see the mod up!
