### ISSUE TITLE
[1.20.1-Fabric] Possible issue with Sodium 0.5.1 ?

### ISSUE THREAD

**Issue by hyperdotbat** [LizIsTired/cave_dust#18]
https://pastebin.com/F1AUfdjA

**Comment by LizIsTired** [comment]
Hi, I had a look and with both your version and the newest version of Sodium I couldn't replicate the issue. 

Could you attempt to replicate the issue with as few mods as possible using the "thanos method" or "binary search"?

A binary search can be used to quickly find a specific mod causing trouble, which can be especially useful when logs don't give a conclusive answer to your issue.

Start by removing or disabling half of your mods, then test if the problem still occurs. If it does, remove half of the remaining mods and test again. If it doesn't, add back half of the mods you just removed.

Keep in mind you don't have to stick strictly to halves each time, and may have to enable some library mods like Fabric API out of order. In this case you need to have Cave Dust still.

By repeating this on an increasingly smaller set of mods, you'll find the problematic mod within a few iterations.

And then send me the smallest list of mods that still crash the game please.

**Comment by LizIsTired** [comment]
@HaipaDev is this still an issue for you? If not I'll be closing this ticket.

**Comment by hyperdotbat** [comment]
Havent checked in a while, its fine if you close it
