### ISSUE TITLE
Unable to download 1.18.2 version

### ISSUE THREAD

**Issue by t16229a** [LizIsTired/cave_dust#2]
When trying to download a file, it redirects to the following window: 
![Снимок экрана 2022-03-25 073909](https://user-images.githubusercontent.com/76599432/160061216-50fefa3d-5bca-45e0-a3a5-38456317613f.jpg)

**Comment by LizIsTired** [comment]
This is something I'm working with the Modrinth team about, I'll provide updates when I have them :)
In the meantime, there's 1.18.2 version on CurseForge

**Comment by t16229a** [comment]
Thanks for your response, i'll look for it on CurseForge. Best of luck with your projects!

**Comment by LizIsTired** [comment]
I've since updated the mod so it's got new downloads, should be fixed :)
