### ISSUE TITLE
World wont load using 2.0.3 (Minecraft version 1.20.1, using quilt)

### ISSUE THREAD

**Issue by NolanHewitt** [LizIsTired/cave_dust#23]
When selecting any world, the game is stuck once it reaches 100%. The game doesn't crash and windows doesn't say the game isn't responding, I just have to manually exit the window. Using version 2.0.1 crashes on start up, version 1.4.1 works normally.
[latest.log](https://github.com/LizIsTired/cave_dust/files/14047365/latest.log)

**Comment by LizIsTired** [comment]
use the latest version, 2.0.4
