### ISSUE TITLE
Can Not Move or Access Inventory

### ISSUE THREAD

**Issue by CaptainPyro32** [LizIsTired/cave_dust#25]
mod works until i load a resource pack and does not matter what resource pack it will make it to where keys on the keyboard do not work and when disabling resource packs the issue stays until i delete some game data

**Comment by GwendiWendi** [comment]
I get the same issue

**Comment by LizIsTired** [comment]
yeahhhh not sure why this is happening, what versions are you guys on?
could you send a log?

**Comment by willjouo** [comment]
Same issue here with `cavedust-2.0.0.jar`. I have a lot of mods and if I disable cave dust everything works again.

**Comment by matteo335** [comment]
I saw several people having this issue in 1.20.1 Forge 47.2.20

**Comment by LizIsTired** [comment]
friends, that version doesn't work
any version on 1.20.1 currently doesn't work, I'll port the fix onto 1.20.1 tonight

**Comment by LizIsTired** [comment]
fixed with latest release, pending approval

**Comment by LizIsTired** [comment]
has this fixed everyone's issues? @willjouo @CaptainPyro32 @GwendiWendi @matteo335

**Comment by tr1kright** [comment]
Yes, everything works, thank you <3
