### ISSUE TITLE
Update to 1.20.4 Fabric Please 

### ISSUE THREAD

**Issue by sternschnaube** [LizIsTired/cave_dust#26]

**Comment by LizIsTired** [comment]
what 
<img width="113" alt="image" src="https://github.com/LizIsTired/cave_dust/assets/13466206/7ce6ac35-d17d-42d6-b213-09713e11cee4">

**Comment by LizIsTired** [comment]
https://www.curseforge.com/minecraft/mc-mods/cave-dust/files/5040250

**Comment by venaminecraft** [comment]
Thanks, Modrinth is missing 😊 

![image](https://github.com/LizIsTired/cave_dust/assets/120551916/eabb8336-5348-4642-b185-10b9c46a4bf7)

**Comment by LessThanBenji** [comment]
(just an fyi -- modrinth is still missing the file for Fabric 1.20.4)
