### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Pie-Not-Lie** [LizIsTired/cave_dust#30]
Needs compatibility with 1.21

**Comment by deffcolony** [comment]
@Pie-Not-Lie 

I am also waiting patiently for the new update so it supports 1.21

**Comment by vico93** [comment]
Was updated. Can close the issue

**Comment by deffcolony** [comment]
1.21 Fabric Update confirmed at: https://modrinth.com/mod/cave-dust/version/YS7mMAIj

Issue can be closed now. Thanks
