### ISSUE TITLE
Compatibility with Dusty

### ISSUE THREAD

**Issue by vico93** [LizIsTired/cave_dust#31]
Seems like having both Cave Dust and @Gibatron's [Dusty](https://github.com/Gibatron/dust/issues) cause the following mixin error to happen at startup:

```
RuntimeException: Non-unique Mixin config name dust.mixins.json used by the mods cavedust and dust
<html>at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:91)<br>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
```

Relevant issue on Dusty side: https://github.com/Gibatron/dust/issues/2

**Comment by LizIsTired** [comment]
Will be fixed in 3.0.1, found the issue.

**Comment by noWickedfortheRest** [comment]
Thanks for sorting this out.

**Comment by LizIsTired** [comment]
No worries, fix will be available over the next few days or tonight depending on if I can be bothered haha yk how it is
