### ISSUE TITLE
Suggestion: dust particle

### ISSUE THREAD

**Issue by meuaky** [LizIsTired/cave_dust#32]
Make the dust particle a different one from the White Ash, the basalt deltas have a lot of lag with the white ash particle enabled, so when i disable it i dont see the cave dust, a solution can be make a dust particle, it can be the same texture as the ash

**Comment by LizIsTired** [comment]
what

**Comment by meuaky** [comment]
> what
i misslick post, im editing it srry

**Comment by LizIsTired** [comment]
cave dust only works in the overworld
if you're lagging it's because you can't handle the normal amount of particles in basalt delta

**Comment by meuaky** [comment]
ye, but with a dust particle i can disable the white ash and enable dust,
 playing normally

**Comment by LizIsTired** [comment]
how would you disable only the white ash?

**Comment by meuaky** [comment]
sodium extra let you disable specific particles

**Comment by LizIsTired** [comment]
for context, this is exactly what I did a few updates ago, there is a separate particle literally called cave dust that is the same texture but floats differently, it has no relation to white ash anymore

**Comment by meuaky** [comment]
oh, i didnt see that srry

**Comment by LizIsTired** [comment]
Can I close this issue @meuaky
