### ISSUE TITLE
White Ash not working

### ISSUE THREAD

**Issue by Avivzv2011** [LizIsTired/cave_dust#33]
I tried doing white ash and it dosen't work, only a few work...

**Comment by LizIsTired** [comment]
What do you mean? Are you changing the settings using the in-game mod menu config? Are you on Forge or Fabric or Quilt? What version of Minecraft? What version of the mod?

**Comment by Avivzv2011** [comment]
I saw it was just my particles as minimal

**Comment by Avivzv2011** [comment]
I saw it was just my particles as minimal
