### ISSUE TITLE
Save particleID as the particle name instead of a number

### ISSUE THREAD

**Issue by NolanHewitt** [LizIsTired/cave_dust#34]
With the current system where it saves as a number, I sometimes find that the cave dust particle has turned into something else when I install new mods or remove other mods. Saving it as the id name "cavedust:cave_dust" if possible would be good.

**Comment by LizIsTired** [comment]
Unfortunately the way I iterate through the particles uses the registry, the registry can change when mods update or when new mods are installed or removed. The way around this is to make a dynamic map for the registry IDs but that's such a pain in the rear that honestly it's not worth it. The current working method is just to reset the config by clicking the reset button, but maybe I'll have a look at it when I have some more free time. Thank you for understanding.

**Comment by CarlosAHT** [comment]
I have the same problem, and in my case, reset settings doesn't work 'cause the cavedust:dust particle ID (109) has been overlaid by another mod, deleting the config folder doesn't work too, so, I can't fix it (and If I try to change the particle in Mod Menu, after some iterations the game crash).

**Comment by AViewFromTheTop** [comment]
Hey!
Would really appreciate if this could get fixed.
This exact issue is, to a degree, what you had seen in earlier Minecraft versions where one block ID gets changed to another, and you get the new block instead across updates. Obviously not a common circumstance, but whatever.
In any case, please use Resource Locations instead. This has caused very annoying issues for my mod’s players and is honestly becoming unacceptable. Especially when certain particles require explicitly defined ParticleOptions which causes the game to crash.

**Comment by LizIsTired** [comment]
Yeah except I don't owe anything to anyone, I said I'd look at when I have time, when I've been homeless for the past 6 months trying to find a place to live. So it'll get fixed when it gets fixed, which will likely be when I've moved in to my new place. Once again, thank you for understanding, I will get to this when I can.

**Comment by NolanHewitt** [comment]
No worries, life comes first. Take care.

**Comment by LizIsTired** [comment]
I'll have a look tonight though, see what I can do. No promises of an update any time soon because it'll be a big one. Need to redo the UI and internals and update to 1.21.3.

**Comment by LizIsTired** [comment]
Ok so, I've rewritten the config to allow for a dynamic list of particles in the registry, using Resource Location on Forge and Identifier on Fabric. The only problem is once again iterating through the list. I'm still learning Java so bear with me while I figure it out. But the UI and 1.21.3 are both fine now, just need to figure this out.
