### ISSUE TITLE
1.21.1

### ISSUE THREAD

**Issue by nijahplays** [LizIsTired/cave_dust#36]
Title

**Comment by Hiroyugane** [comment]
For a quick workaround, you can change the version requirement inside the .jar (fabric.mod.json)
I've done some playtesting in my modpack. My game crashed twice in some very random spots. Not necessarily the fault of this mod tho. 
Just use at your own caution and let's hope it gets an actual update at some point.

```
  "depends": {
    "fabricloader": "\u003e\u003d0.14.5",
    "fabric": "*",
    "minecraft": "*1.21.1*",
    "java": "\u003e\u003d17"
  },
```

**Comment by LizIsTired** [comment]
consider this the official 1.21.1 update announcement! support will be added in the next week :)

**Comment by SussyBob** [comment]
has its been updated? Bcs i still get crashes (3.0.0)

**Comment by ghost** [comment]
> consider this the official 1.21.1 update announcement! support will be added in the next week :)

"3 weeks ago" 😭😭😭😭

**Comment by LizIsTired** [comment]
Minecraft updated to 1.21.3, so Cave Dust has been updated for that version. Older versions won't get updates as it's too much work to maintain for just one person.
