### ISSUE TITLE
[Mod compatibility] Don't use the particle id in configuration file

### ISSUE THREAD

**Issue by florianreuth** [LizIsTired/cave_dust#37]
The 1.21 fabric branch uses the internal registry id for saving the used particle in the config file (see https://github.com/LizIsTired/cave_dust/blob/1.21_fabric/src/main/java/net/lizistired/cavedust/CaveDustConfig.java#L133), this will break when other mods add new particle types as all ids will shift. 

Specifically, my mod creates a temporary particle type that shouldn't be created by other mods. This can lead to errors in certain situations (see https://github.com/ViaVersion/ViaFabricPlus/issues/549 and my code in https://github.com/ViaVersion/ViaFabricPlus/blob/main/src/main/java/de/florianmichael/viafabricplus/fixes/versioned/visual/FootStepParticle1_12_2.java#L106).

In general you should rather use the particle name/identifier for the config file to ensure compatibility with my (and other mods).

**Comment by SnowCutieOwO** [comment]
https://mclo.gs/4tkb8y3
Still crashed. Using `3.0.0` for 1.21-Fabric
:(

**Comment by LizIsTired** [comment]
Please update to 3.0.1 it fixes this issue :)

**Comment by SnowCutieOwO** [comment]
> Please update to 3.0.1 it fixes this issue :)

Could you please make a backport for 1.21? :(

**Comment by LizIsTired** [comment]
Unfortunately not, I have so many people asking for backports of specific versions, if I backported it for you I'd have to do it for everyone and that's too much for just one person (I'm also moving this week) but I can see if I can do something when I'm settled in but that could be a while. Thank you for your understanding.
