### ISSUE TITLE
[Suggestion] Add small chance for a bigger particle

### ISSUE THREAD

**Issue by Rafii2198** [LizIsTired/cave_dust#5]
If it is possible then it would be cool if there was a small chance for a particle from flying sand/gravel to spawn instead of normal one. It kinda looks like clamped dust so it would go very well with the theme.
If the chance would be configurable then it would be awesome!

**Comment by LizIsTired** [comment]
Thanks for your suggestion! 
This is something I can absolutely do! I worry about complication in the config but it's already convoluted so it wouldn't be a massive change haha. Unless I run into issues, this should be in the next update!

**Comment by LizIsTired** [comment]
Unfortunately, there isn't a method that allows you to change the scale of particles! So this feature will not be added.

**Comment by Rafii2198** [comment]
Oh, I didn't mean about scaling it, I meant that the particle that is spawn on sand or gravel in the air is just bigger than the one used as the dust, and it would just have a small spawn rate that would serve as a bigger dust
